name: Gradle Package

on:
  pull_request:
    branches:
      - main
    types: [ closed ]

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: 'echo "$GRADLE_PROPERTIES" >> gradle.properties'
        shell: bash
        env:
          GRADLE_PROPERTIES: ${{secrets.GRADLE_PROPERTIES}}

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Gradle release
        uses: gradle/gradle-build-action@v2
        with:
          arguments: release -Prelease.disableChecks -Prelease.localOnly

      - name: Gradle build and test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build validatePlugin functionalTest integrationTest buildDashboard

      - name: Gradle publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish githubRelease publishDocs examples -PgithubToken=${{secrets.GITHUB_TOKEN}}

      - name: Publish tests
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'

      - name: Update Documentation
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updating README and examples.
          branch: main
          file_pattern: 'README.md examples/*.gradle'
          status_options: '--untracked-files=no'
