name: Run Gradle on PRs

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: 'echo "ref: $GITHUB_REF, ref_name: $GITHUB_REF_NAME, type: $GITHUB_REF_TYPE"'
        shell: bash

      - run: 'echo "$GRADLE_PROPERTIES" >> gradle.properties'
        shell: bash
        env:
          GRADLE_PROPERTIES: ${{secrets.GRADLE_PROPERTIES}}

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Gradle build and test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build validatePlugin functionalTest buildDashboard
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.CIO_AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.CIO_AWS_SECRET_ACCESS_KEY}}

      - name: Publish tests
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
