name: Run Gradle on PRs

on:
  pull_request

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
             echo "$GRADLE_PROPERTIES" > gradle.properties
        name: 'Write gradle.properties file'
        shell: bash
        env:
          GRADLE_PROPERTIES: ${{secrets.GRADLE_PROPERTIES}}

      - run: |
             mkdir -p $HOME/.snowsql
             echo "$SNOW_CONFIG" > $HOME/.snowsql/config
        name: 'Write snow-config file'
        shell: bash
        env:
          SNOW_CONFIG: ${{secrets.SNOW_CONFIG}}

      - run: 'ls -l $HOME'
        name: 'Look at filesystem'
        shell: bash

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Gradle build and test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build validatePlugin functionalTest integrationTest buildDashboard

      - name: Publish tests
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
