name: Run Gradle on PRs

on:
  pull_request

env:
  ORG_GRADLE_PROJECT_snowflake_user: ${{ SNOWFLAKE_USER }}
  ORG_GRADLE_PROJECT_snowflake_password: ${{SNOWFLAKE_PASSWORD}}
  ORG_GRADLE_PROJECT_snowflake_account: ${{SNOWFLAKE_ACCOUNT}}
  ORG_GRADLE_PROJECT_publish_url: ${{PUBLISH_URL}}
  AWS_ACCESS_KEY_ID: ${{AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{AWS_SECRET_ACCESS_KEY}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Gradle build and test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build functionalTest
