name: Gradle Package

on:
  pull_request:
    branches:
      - main
    types: [ closed ]

env:
  ORG_GRADLE_PROJECT_account: ${{secrets.SNOWFLAKE_ACCOUNT}}
  ORG_GRADLE_PROJECT_snowflake_user: ${{secrets.SNOWFLAKE_USER}}
  ORG_GRADLE_PROJECT_snowflake_password: ${{secrets.SNOWFLAKE_PASSWORD}}
  ORG_GRADLE_PROJECT_snowflake_account: ${{secrets.SNOWFLAKE_ACCOUNT}}
  ORG_GRADLE_PROJECT_publish_url: ${{secrets.PUBLISH_URL}}
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Gradle release
        uses: gradle/gradle-build-action@v2
        with:
          arguments: release

      - name: Gradle publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build publish
