name: Gradle Package

on:
  pull_request:
    branches:
      - main
    types: [ closed ]

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: 'echo "$GRADLE_PROPERTIES" >> gradle.properties'
        shell: bash
        env:
          GRADLE_PROPERTIES: ${{secrets.GRADLE_PROPERTIES}}

      - name: Gradle release
        uses: gradle/gradle-build-action@v2
        with:
          arguments: release -Prelease.disableChecks -Prelease.localOnly

      - name: Gradle publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build publish githubRelease buildDashboard -PgithubToken=${{secrets.GITHUB_TOKEN}}

      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path:|
          build/reports/buildDashboard/
          plugin/build/reports/
