name: Gradle Package

on:
  pull_request:
    branches:
      - main
    types: [ closed ]

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  gradle_build:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          mkdir -p $HOME/.gradle
          echo "$GRADLE_PROPERTIES" > $HOME/.gradle/gradle.properties
        name: 'Write gradle.properties file'
        shell: bash
        env:
          GRADLE_PROPERTIES: ${{secrets.GRADLE_PROPERTIES}}

      - run: |
          mkdir -p $HOME/.snowsql
          echo "$SNOW_CONFIG" > $HOME/.snowsql/config
        name: 'Write .snowsql/config file'
        shell: bash
        env:
          SNOW_CONFIG: ${{secrets.SNOW_CONFIG}}

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Gradle release
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: release -Prelease.disableChecks -Prelease.localOnly --scan

      - name: Gradle build and test
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build validatePlugin functionalTest integrationTest buildDashboard --scan

      - name: Gradle publish
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: publish githubRelease publishDocs examples --scan -PgithubToken=${{secrets.GITHUB_TOKEN}} -S

      - name: Publish tests
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'

      - name: Update Documentation
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updating README and examples.
          branch: main
          file_pattern: 'README.md examples/*.gradle'
          status_options: '--untracked-files=no'

  run_example:
    #if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory: [java-manual, java, java-testing, groovy, scala, kotlin]
        #directory: [java]

    steps:
      # Should really make these reusable
      - uses: actions/checkout@v3

      - id: gradle_properties
        run: |
          mkdir -p $HOME/.gradle
          echo "$GRADLE_PROPERTIES" > $HOME/.gradle/gradle.properties
        name: 'Write gradle.properties file'
        shell: bash
        env:
          GRADLE_PROPERTIES: ${{secrets.GRADLE_PROPERTIES}}

      - id: snowsql_config
        run: |
          mkdir -p $HOME/.snowsql
          echo "$SNOW_CONFIG" > $HOME/.snowsql/config
        name: 'Write .snowsql/config file'
        shell: bash
        env:
          SNOW_CONFIG: ${{secrets.SNOW_CONFIG}}

      - name: ${{ matrix.directory }}
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: matrixStrategy -Psnowflake.useEphemeral=true -S
          build-root-directory: examples/${{ matrix.directory }}
